# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.0.2
    hooks:
      - id: golangci-lint-full
        args: ["--timeout=10m", "--config=.golangci.yml"]
  - repo: local
    hooks:
      - id: generate-manifest
        language: system
        name: generate manifest
        entry: make manifest
