apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-scale-to-zero-plugin
  namespace: cnpg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg-scale-to-zero-sidecar-role
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  - scheduledbackups
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-scale-to-zero-plugin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnpg-scale-to-zero-sidecar-role
subjects:
- kind: ServiceAccount
  name: cnpg-scale-to-zero-plugin
  namespace: cnpg-system
---
apiVersion: v1
data:
  SIDECAR_IMAGE: Z2hjci5pby94YXRhaW8vY25wZy1pLXNjYWxlLXRvLXplcm8tc2lkZWNhcjptYWlu
kind: Secret
metadata:
  name: scale-to-zero-config-tcb898m758
  namespace: cnpg-system
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/pluginClientSecret: scaletozero-client-tls
    cnpg.io/pluginPort: "9090"
    cnpg.io/pluginServerSecret: scaletozero-server-tls
  labels:
    app: scale-to-zero
    cnpg.io/pluginName: cnpg-i-scale-to-zero.xata.io
  name: scale-to-zero
  namespace: cnpg-system
spec:
  ports:
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: scale-to-zero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scale-to-zero
  name: scale-to-zero
  namespace: cnpg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-to-zero
  strategy: {}
  template:
    metadata:
      labels:
        app: scale-to-zero
    spec:
      containers:
      - args:
        - plugin
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        env:
        - name: LOG_LEVEL
          value: info
        - name: SIDECAR_CPU_REQUEST
          value: 50m
        - name: SIDECAR_CPU_LIMIT
          value: 200m
        - name: SIDECAR_MEMORY_REQUEST
          value: 64Mi
        - name: SIDECAR_MEMORY_LIMIT
          value: 64Mi
        envFrom:
        - secretRef:
            name: scale-to-zero-config-tcb898m758
        image: ghcr.io/xataio/cnpg-i-scale-to-zero:main
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          tcpSocket:
            port: 9090
          timeoutSeconds: 5
        name: cnpg-i-scale-to-zero
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 9090
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: cnpg-scale-to-zero-plugin
      volumes:
      - name: server
        secret:
          secretName: scaletozero-server-tls
      - name: client
        secret:
          secretName: scaletozero-client-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scaletozero-client
  namespace: cnpg-system
spec:
  commonName: scaletozero-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cnpg-scale-to-zero-selfsigned-issuer
  renewBefore: 360h
  secretName: scaletozero-client-tls
  usages:
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scaletozero-server
  namespace: cnpg-system
spec:
  commonName: scale-to-zero
  dnsNames:
  - scale-to-zero
  - scale-to-zero.cnpg-system
  - scale-to-zero.cnpg-system.svc
  - scale-to-zero.cnpg-system.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cnpg-scale-to-zero-selfsigned-issuer
  renewBefore: 360h
  secretName: scaletozero-server-tls
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cnpg-scale-to-zero-selfsigned-issuer
  namespace: cnpg-system
spec:
  selfSigned: {}
