apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    xata.io/scale-to-zero-enabled: "true"
    xata.io/scale-to-zero-inactivity-minutes: "2"
spec:
  instances: 2
  enableSuperuserAccess: true

  plugins:
  - name: cnpg-i-scale-to-zero.xata.io

  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-example
  namespace: default
spec:
  schedule: "0 0 2 * * *"  # Daily at 2 AM (seconds, minutes, hours, day of month, month, day of week)
  cluster:
    name: cluster-example
  backupOwnerReference: self
