---
# RBAC for the cluster's sidecar to update cluster resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-example-scale-to-zero-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnpg-scale-to-zero-sidecar-role
subjects:
- kind: ServiceAccount
  name: cluster-example
  namespace: default
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    xata.io/scale-to-zero-enabled: "true"
    xata.io/scale-to-zero-inactivity-minutes: "2"
spec:
  instances: 2
  enableSuperuserAccess: true

  plugins:
  - name: cnpg-i-scale-to-zero.xata.io

  storage:
    size: 1Gi
