# RBAC Template for Scale-to-Zero Clusters
#
# This template creates the necessary RBAC permissions for each cluster that uses
# the scale-to-zero plugin. The sidecar injected into the cluster pod needs permission
# to update cluster resources for hibernation.
#
# Usage:
# 1. Copy this file: cp rbac-template.yaml my-cluster-rbac.yaml
# 2. Replace placeholders:
#    - CLUSTER_NAME: with your cluster name (e.g., "my-cluster")
#    - NAMESPACE: with your cluster's namespace (e.g., "default")
# 3. Apply: kubectl apply -f my-cluster-rbac.yaml
#
# Alternatively, use sed for quick replacement:
# sed 's/CLUSTER_NAME/my-cluster/g; s/NAMESPACE/default/g' rbac-template.yaml | kubectl apply -f -
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: CLUSTER_NAME-scale-to-zero-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnpg-scale-to-zero-sidecar-role  # This ClusterRole is created by the plugin installation
subjects:
- kind: ServiceAccount
  name: CLUSTER_NAME  # CloudNativePG creates a service account with the same name as the cluster
  namespace: NAMESPACE
