name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Run linting
        run: make lint
#   manifest:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Install kustomize
#         run: |
#           curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
#           sudo mv kustomize /usr/local/bin/

#       - name: Generate manifest
#         run: make manifest

#       - name: Validate manifest
#         run: make validate-manifest

#       - name: Upload manifest artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: kubernetes-manifest
#           path: |
#             manifest.yaml
#           retention-days: 7
