name: Cleanup Old Container Images

on:
  schedule:
    # Run weekly on Mondays at 12 PM UTC (noon)
    - cron: "0 12 * * 1"
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: ghcr.io
  # Shared cleanup configuration
  PACKAGES: "cnpg-i-scale-to-zero,cnpg-i-scale-to-zero-sidecar"
  EXCLUDE_TAGS: "v*,latest,main"
  DELETE_TAGS: "main-*"

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Preview cleanup (dry run)
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ${{ env.PACKAGES }}
          exclude-tags: ${{ env.EXCLUDE_TAGS }}
          delete-tags: ${{ env.DELETE_TAGS }}
          delete-untagged: true
          log-level: "info"
          dry-run: true

  cleanup:
    needs: preview
    runs-on: ubuntu-latest
    environment:
      name: image-cleanup-approval
      url: https://github.com/${{ github.repository }}/packages
    permissions:
      contents: read
      packages: write
    steps:
      - name: Cleanup old container images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ${{ env.PACKAGES }}
          exclude-tags: ${{ env.EXCLUDE_TAGS }}
          delete-tags: ${{ env.DELETE_TAGS }}
          delete-untagged: true
          log-level: "info"
          dry-run: false
