name: PR Image Build

# Automatically builds images when 'build-images' label is added to a PR
# Requires approval in 'pr-image-build' environment

on:
  pull_request:
    types: [labeled]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PLUGIN: ${{ github.repository }}
  IMAGE_NAME_SIDECAR: ${{ github.repository }}-sidecar

jobs:
  docker-build:
    if: contains(github.event.label.name, 'build-images')
    uses: ./.github/workflows/docker-build.yml
    with:
      image_tag: ${{ format('pr-{0}-{1}', github.event.number, github.sha) }}
      should_push: true
      generate_manifest: true
      manifest_name: kubernetes-manifest-pr-${{ github.event.number }}
      environment: pr-image-build
    secrets: inherit

  notify-pr:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Comment on PR with image details
        uses: actions/github-script@v7
        with:
          script: |
            const tag = `pr-${{ github.event.number }}-${{ github.sha }}`.substring(0, 50); // Truncate to reasonable length
            const body = `🚀 **PR Images Built Successfully!**

            **Image Tags:**
            - Plugin: \`ghcr.io/xataio/cnpg-i-scale-to-zero:${tag}\`
            - Sidecar: \`ghcr.io/xataio/cnpg-i-scale-to-zero-sidecar:${tag}\`

            **Manifest:** Download the \`kubernetes-manifest-pr-${{ github.event.number }}\` artifact from this workflow run.

            These images are for testing purposes and will be automatically cleaned up when the PR is closed.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
